/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinGUI

import tornadofx.*
import kotlinGUI.styles.VisibleBorder
import saveableProperties.PropertiesSaver

fun main(args: Array<String>) {
    PropertiesSaver.LoadProperties()
    launch<VisualApplication>(args)
}

class VisualApplication: App(MainForm::class, VisibleBorder::class)

