/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinGUI

import tornadofx.*
//import ExternalDevices

fun main(args: Array<String>) {
    launch<VisualApplication>(args)
    println("hello")
    var port = PortCOM(SettingsCOM())
    //port.OpenPort()
}


class VisualApplication: App(MainForm::class)

