/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinGUI

import tornadofx.*
//import ExternalDevices

fun main(args: Array<String>) {
    //launch<VisualApplication>(args)
    launch<MyApp>(args)
    println("hello")
    var port = PortCOM(SettingsCOM())
    port.OpenPort()
}


/* class VisualApplication: App(MainForm::class)

class MainForm: View()
{
    override val root = vbox {
        button("big red btn")
    }
} */

class MyApp: App(MyView::class)

class MyView: View() {
    override val root = vbox {
        button("big red btn")
        label("Waiting")
    }
}